version: "3"

services:
  redis:
    image: redis:7.2.5-alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  server:
    build: .
    container_name: example-server
    depends_on:
      - redis
    restart: always
    ports:
      - 8080:8080
    environment:
      - REDIS_ADDR=redis:6379
    volumes:
      - gomod:/go/pkg/mod

volumes:
  redis:
  gomod:
